### ISSUE TITLE
 The "SDK components for creating applications for different Android platforms" option is disabled in Android Studio (on Ubuntu 24.04). 

### ISSUE THREAD

**Issue by Marietto2008** [3052/widevine#2]
Hello.

I know that this question is not very pertinent with this repo,but I want to try to ask anyway,otherwise I can't continue. 

When I try to install Android Studio (on Ubuntu 24.04),I see that I can only use the Android API 35 ; I can't select abi x86 and api level = 24. The "SDK components for creating applications for different Android platforms" option is disabled. 

How can I enable it ?

**Comment by 3052** [comment]
you're not creating an application, you're creating a virtual device
